<?php

namespace AppBundle\Repository;

/**
 * cadcategRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cadcategRepository extends \Doctrine\ORM\EntityRepository
{
}
