<?php

namespace AppBundle\Repository;

/**
 * cadunidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cadunidaRepository extends \Doctrine\ORM\EntityRepository
{
}
