imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: customer
        connections:
            default:
                driver:   pdo_mysql
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
            customer:
                driver: pdo_pgsql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/*'
            output: js/bootstrap.js

        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.min.css'
            output: css/bootstrap.css
        custom_js:
            inputs:
                - '%kernel.root_dir%/../vendor/build/js/custom.min.js'
            output: js/custom.js
        custom_css:
            inputs:
                - '%kernel.root_dir%/../vendor/build/css/custom.min.css'
            output: css/custom.css
        jquery_css:
            inputs:
                - '%kernel.root_dir%/../vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css'
            output: css/jquery.css
            
        jquery:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.min.js'
                - '%kernel.root_dir%/../vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js'
            output: js/jquery.js
            
        font_awesome_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/css/font-awesome.min.css'
            output: css/font-awesome.css
            
            filters: [cssrewrite]
            
        bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
            output: "fonts/glyphicons-halflings-regular.woff"
            
        fontawesome_webfont_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf'
            output: "fonts/fontawesome-webfont.ttf"
        fontawesome_webfont_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.eot'
            output: "fonts/fontawesome-webfont.eot"
        fontawesome_webfont_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.svg'
            output: "fonts/fontawesome-webfont.svg"
        fontawesome_webfont_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff'
            output: "fonts/fontawesome-webfont.woff"
        fontawesome_webfont_woff2:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff'
            output: "fonts/fontawesome-webfont.woff2"
            
        skycons:
            inputs:
                - '%kernel.root_dir%/../vendor/skycons/skycons.js'
            output: js/skycons.js
            
        icheck:
            inputs:
                - '%kernel.root_dir%/../vendor/iCheck/icheck.min.js'
            output: js/icheck.js
            
        fastclick:
            inputs:
                - '%kernel.root_dir%/../vendor/fastclick/lib/fastclick.js'
            output: js/fastclick.js
            
        gauge:
            inputs:
                - '%kernel.root_dir%/../vendor/gauge/dist/gauge.min.js'
            output: js/gauge.js
            
        bootstrap_progressbar_js:
            inputs:
                - '%kernel.root_dir%/../vendor/bootstrap-progressbar/bootstrap-progressbar.min.js'
            output: js/bootstrap-progressbar.js
 